FROM phpmyadmin/phpmyadmin

LABEL maintainer="Melkov Aleksandr <a.melkov@richbrains.net>"

# Add volume for sessions to allow session persistence
VOLUME /sessions

# We expose phpMyAdmin on port 80
EXPOSE 80
